Develop
nicolopezca/repo_videos pull request #1
Opened 2021-11-10 12:47 UTC by nicolopezca

Primera PR con dos ejs

2021-11-11 08:25 UTC, Carlos-Monfort approved these changes

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +//// --------------------------------------
No dejemos código comentado en las PRs. Si este ejercicio no vamos al final a realizarlo borra todo el código relacionado con él para que no quede comentado.

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +enum Suit: String {
Si ya está hecho, borra la línea con el comentario del TODO

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +
Borramos todo el código comentado y los saltos de línea innecesarios

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +
Borra la línea con el TODO.

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +
Vamos a seguir en todo momento la guía de estilo de RayWanderlich: https://github.com/raywenderlich/swift-style-guide#spacing

Por eso vamos a evitar el espacio entre variable y el tipo.

DE 

`let coinPurse : [Coin] `

A

`let coinPurse: [Coin] `

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +}
Para el naming de las variables vamos a utilizar solo el inglés, cambiemos esos nombres en castellano por su equivalente en inglés

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +money
Borremos saltos de línea innecesarios

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/06 - Challenge - Switch Statements.xcplaygroundpage/Contents.swift
> +
Borrar saltos de línea innecesarios

2021-11-11 08:25 UTC, Carlos-Monfort commented on ejs_numerations/06 - Challenge - Switch Statements.xcplaygroundpage/Contents.swift
> +}
Borrar salto de línea innecesario

2021-11-11 08:27 UTC, Carlos-Monfort requested changes

2021-11-11 08:27 UTC, Carlos-Monfort commented on ejs_numerations/06 - Challenge - Switch Statements.xcplaygroundpage/Contents.swift
> +        switch movimiento {
Nombre de variable en castellano

2021-11-11 09:01 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +//// --------------------------------------
Hecho!

2021-11-11 09:01 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +enum Suit: String {
Hecho!

2021-11-11 09:01 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +
Hecho!

2021-11-11 09:02 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +
Hecho!

2021-11-11 09:04 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +
Perfe, es algo a tener en cuenta si.

2021-11-11 09:47 UTC, nicolopezca commented on ejs_numerations/06 - Challenge - Switch Statements.xcplaygroundpage/Contents.swift
> +        switch movimiento {
perfe

2021-11-11 09:50 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +}
Entendido

2021-11-11 09:51 UTC, nicolopezca commented on ejs_numerations/03 - Challenge - Enumerations.xcplaygroundpage/Contents.swift
> +money
Hecho!

2021-11-12 10:52 UTC, Carlos-Monfort approved these changes

2021-11-15 09:54 UTC, Carlos-Monfort approved these changes

2021-11-15 10:02 UTC, merged